config/routes.rb
Rails.application.routes.draw do
  # SPP
  get '/spp', to: 'spp#index', as: 'spp_index'
  resources :spp_payments
  resources :spp_invoices
  resources :spp_categories
  resources :spp_students
  resources :spp_batches

  # Campaign
  resources :categories
  resources :donations
  resources :campaigns do
    member do
      get :contribute
    end
  end
  resources :comments

  # System
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :users
  resources :posts
  get "up" => "rails/health#show", as: :rails_health_check
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  belongs_to :category
  mount_uploader :picture, ImageUploader
  has_rich_text :content
  has_many :donations, dependent: :destroy
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :campaigns
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_rich_text :content
end

app/models/donation.rb
class Donation < ApplicationRecord
  belongs_to :campaign
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :pict, ImageUploader
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_rich_text :content
end

app/models/spp_batch.rb
class SppBatch < ApplicationRecord
  def start_at_year
    start_at.year
  end
end

app/models/spp_category.rb
class SppCategory < ApplicationRecord
end

app/models/spp_invoice.rb
class SppInvoice < ApplicationRecord
  belongs_to :spp_student
  belongs_to :spp_category
  has_many :spp_payments
end

app/models/spp_payment.rb
class SppPayment < ApplicationRecord
  belongs_to :spp_batch
  belongs_to :user, optional: true
  belongs_to :spp_student
  belongs_to :spp_invoice
end

app/models/spp_student.rb
class SppStudent < ApplicationRecord
  belongs_to :spp_batch
  has_many :spp_payments
  has_many :spp_invoices

  mount_uploader :pict, ImageUploader

  after_create :create_spp_invoices

  def create_spp_invoices
    spp_category = SppCategory.find_or_create_by(title: "SPP")

    spp_invoice = SppInvoice.create(
      spp_student_id: id,
      spp_category_id: spp_category.id,
      amount: 12_000_000,
      paid_amount: 0,
      status: "NEW",
    )

    # Create SPP Payments for the next 12 months
    (0..11).each do |i|
      due_date = spp_batch.start_at + i.months
      SppPayment.create!(
        spp_batch_id: spp_batch_id,
        spp_student_id: id,
        spp_invoice_id: spp_invoice.id,
        amount: 1_000_000,
        # user_id diambil dari user yg login
        # tipe : harus dimasukkan manual oleh bendahara
        # pay_at : harus dimasukkan manual oleh bendahara
      )
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy

  def admin?
    role == 'ADMIN'
  end

  def user?
    role == 'USER'
  end
end

app/controllers/spp_controller.rb
class SppController < ApplicationController

  def index
  end

end

app/controllers/spp_payments_controller.rb
class SppPaymentsController < ApplicationController
  before_action :set_spp_payment, only: %i[ show edit update destroy ]

  # GET /spp_payments or /spp_payments.json
  def index
    @spp_payments = SppPayment.order(id: :desc).paginate(page: params[:page])
  end

  # GET /spp_payments/1 or /spp_payments/1.json
  def show
  end

  # GET /spp_payments/new
  def new
    @spp_payment = SppPayment.new
  end

  # GET /spp_payments/1/edit
  def edit
  end

  # POST /spp_payments or /spp_payments.json
  def create
    @spp_payment = SppPayment.new(spp_payment_params)

    respond_to do |format|
      if @spp_payment.save
        format.html { redirect_to spp_payment_url(@spp_payment), notice: "SPP payment was successfully created." }
        format.json { render :show, status: :created, location: @spp_payment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @spp_payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spp_payments/1 or /spp_payments/1.json
  def update
    respond_to do |format|
      if @spp_payment.update(spp_payment_params)
        format.html { redirect_to spp_payment_url(@spp_payment), notice: "SPP payment was successfully updated." }
        format.json { render :show, status: :ok, location: @spp_payment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @spp_payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spp_payments/1 or /spp_payments/1.json
  def destroy
    @spp_payment.destroy!

    respond_to do |format|
      format.html { redirect_to spp_payments_url, notice: "SPP payment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spp_payment
      @spp_payment = SppPayment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def spp_payment_params
      params.require(:spp_payment).permit(:spp_batch_id, :user_id, :spp_student_id, :spp_invoice_id, :tipe, :amount, :pay_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def idr v
    number_to_currency( v.to_i, unit: "Rp", precision: 0, separator: ",", delimiter: ".", format: "%u%n,-")
  end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/spp_batches_helper.rb
module SppBatchesHelper
end

app/helpers/spp_payments_helper.rb
module SppPaymentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/spp_payments/_form.html.erb
<%= form_with(model: spp_payment) do |form| %>
  <% if spp_payment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(spp_payment.errors.count, "error") %> prohibited this spp_payment from being saved:</h2>

      <ul>
        <% spp_payment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :spp_batch_id, style: "display: block" %>
    <%= form.text_field :spp_batch_id %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :spp_student_id, style: "display: block" %>
    <%= form.text_field :spp_student_id %>
  </div>

  <div>
    <%= form.label :spp_invoice_id, style: "display: block" %>
    <%= form.text_field :spp_invoice_id %>
  </div>

  <div>
    <%= form.label :tipe, style: "display: block" %>
    <%= form.text_field :tipe %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.number_field :amount %>
  </div>

  <div>
    <%= form.label :pay_at, style: "display: block" %>
    <%= form.datetime_field :pay_at %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/spp_payments/_spp_payment.html.erb
<div id="<%= dom_id spp_payment %>">
  <p>
    <strong>SPP batch:</strong>
    <%= spp_payment.spp_batch_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= spp_payment.user_id %>
  </p>

  <p>
    <strong>SPP student:</strong>
    <%= spp_payment.spp_student_id %>
  </p>

  <p>
    <strong>SPP invoice:</strong>
    <%= spp_payment.spp_invoice_id %>
  </p>

  <p>
    <strong>Tipe:</strong>
    <%= spp_payment.tipe %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= spp_payment.amount %>
  </p>

  <p>
    <strong>Pay at:</strong>
    <%= spp_payment.pay_at %>
  </p>

</div>

app/views/spp_payments/edit.html.erb
<h1>Editing spp payment</h1>

<%= render "form", spp_payment: @spp_payment %>

<br>

<div>
  <%= link_to "Show this spp payment", @spp_payment %> |
  <%= link_to "Back to spp payments", spp_payments_path %>
</div>

app/views/spp_payments/index.html.erb
<div id="spp_students" class="album py-5 bg-light">
  <div class="container">

    <h1>SPP payments</h1>

    <table class="table">
      <thead>
        <tr>
          <th>ID</th>
          <th>Angkatan</th>
          <th>Staff</th>
          <th>Murid</th>
          <th>Invoice</th>
          <th>Tipe</th>
          <th>Jumlah</th>
          <th>Tanggal</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @spp_payments.each do |spp_payment| %>
          <tr>
            <td><%= spp_payment.id %></td>
            <td><%= spp_payment.spp_batch.start_at.strftime('%Y') %></td>
            <td><%= spp_payment.user.name %></td>
            <td><%= spp_payment.spp_student.name %></td>
            <td>No <%= spp_payment.spp_invoice_id %></td>
            <td><%= spp_payment.tipe %></td>
            <td><%= idr spp_payment.amount %></td>
            <td><%= spp_payment.pay_at.strftime('%d-%m-%Y') %></td>
            <td>
              <%= link_to "Show", spp_payment, class: "btn btn-primary" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>


    <div class="apple_pagination mt-3">
      <%= will_paginate @spp_payments %>
    </div>
      <%= link_to "New spp payment", new_spp_payment_path, class: "btn btn-success" %>
  </div>
</div>

app/views/spp_payments/new.html.erb
<h1>New spp payment</h1>

<%= render "form", spp_payment: @spp_payment %>

<br>

<div>
  <%= link_to "Back to spp payments", spp_payments_path %>
</div>

app/views/spp_payments/show.html.erb
<%= render @spp_payment %>

<div>
  <%= link_to "Edit this spp payment", edit_spp_payment_path(@spp_payment) %> |
  <%= link_to "Back to spp payments", spp_payments_path %>

  <%= button_to "Destroy this spp payment", @spp_payment, method: :delete %>
</div>