config/routes.rb
Rails.application.routes.draw do
  # SPP
  get '/spp', to: 'spp#index', as: 'spp_index'
  resources :spp_payments
  resources :spp_invoices
  resources :spp_categories
  resources :spp_students
  resources :spp_batches

  # Campaign
  resources :categories
  resources :donations
  resources :campaigns do
    member do
      get :contribute
    end
  end
  resources :comments

  # System
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :users
  resources :posts
  get "up" => "rails/health#show", as: :rails_health_check
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  belongs_to :category
  mount_uploader :picture, ImageUploader
  has_rich_text :content
  has_many :donations, dependent: :destroy
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :campaigns
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_rich_text :content
end

app/models/donation.rb
class Donation < ApplicationRecord
  belongs_to :campaign
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :pict, ImageUploader
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_rich_text :content
end

app/models/spp_batch.rb
class SppBatch < ApplicationRecord
  def start_at_year
    start_at.year
  end
end

app/models/spp_category.rb
class SppCategory < ApplicationRecord
end

app/models/spp_invoice.rb
class SppInvoice < ApplicationRecord
  belongs_to :spp_student
  belongs_to :spp_category
  has_many :spp_payments
end

app/models/spp_payment.rb
class SppPayment < ApplicationRecord
  belongs_to :spp_batch
  belongs_to :user, optional: true
  belongs_to :spp_student
  belongs_to :spp_invoice
end

app/models/spp_student.rb
class SppStudent < ApplicationRecord
  belongs_to :spp_batch
  has_many :spp_payments
  has_many :spp_invoices

  mount_uploader :pict, ImageUploader

  after_create :create_spp_invoices

  def create_spp_invoices
    spp_category = SppCategory.find_or_create_by(title: "SPP")

    spp_invoice = SppInvoice.create(
      spp_student_id: id,
      spp_category_id: spp_category.id,
      amount: 12_000_000,
      paid_amount: 0,
      status: "NEW",
    )

    # Create SPP Payments for the next 12 months
    (0..11).each do |i|
      due_date = spp_batch.start_at + i.months
      SppPayment.create!(
        spp_batch_id: spp_batch_id,
        spp_student_id: id,
        spp_invoice_id: spp_invoice.id,
        amount: 1_000_000,
        # user_id diambil dari user yg login
        # tipe : harus dimasukkan manual oleh bendahara
        # pay_at : harus dimasukkan manual oleh bendahara
      )
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy

  def admin?
    role == 'ADMIN'
  end

  def user?
    role == 'USER'
  end
end

app/controllers/spp_controller.rb
class SppController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def idr v
    number_to_currency( v.to_i, unit: "Rp", precision: 0, separator: ",", delimiter: ".", format: "%u%n,-")
  end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/spp_batches_helper.rb
module SppBatchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/spp/index.html.erb
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">

        <div class="col">
          <div class="card mb-4 shadow-sm">
            <div class="card-body">
              <%= link_to spp_batches_path, class: "stretched-link" do %>
                <span style="color: #789461;">
                  <i class="fas fa-calendar fa-3x mb-3"></i>
                </span>
                <br/>
                Batch
              <% end %>
            </div>
          </div>
        </div>


        <div class="col">
          <div class="card mb-4 shadow-sm">
            <div class="card-body">
              <%= link_to spp_students_path, class: "stretched-link" do %>
                <span style="color: #789461;">
                  <i class="fas fa-user fa-3x mb-3"></i>
                </span>
                <br/>
                Student
              <% end %>
            </div>
          </div>
        </div>

        <div class="col">
          <div class="card mb-4 shadow-sm">
            <div class="card-body">
              <%= link_to spp_categories_path, class: "stretched-link" do %>
                <span style="color: #789461;">
                  <i class="fas fa-school fa-3x mb-3"></i>
                </span>
                <br/>
                Category
              <% end %>
            </div>
          </div>
        </div>


        <div class="col">
          <div class="card mb-4 shadow-sm">
            <div class="card-body">
              <%= link_to spp_invoices_path, class: "stretched-link" do %>
                <span style="color: #789461;">
                  <i class="fas fa-dollar fa-3x mb-3"></i>
                </span>
                <br/>
                Invoice
              <% end %>
            </div>
          </div>
        </div>


        <div class="col">
          <div class="card mb-4 shadow-sm">
            <div class="card-body">
              <%= link_to spp_payments_path, class: "stretched-link" do %>
                <span style="color: #789461;">
                  <i class="fas fa-money-bill-wave fa-3x mb-3"></i>
                </span>
                <br/>
                Payment
              <% end %>
            </div>
          </div>
        </div>


      </div>

    </div>
  </div>