config/routes.rb
Rails.application.routes.draw do
  # SPP
  get '/spp', to: 'spp#index', as: 'spp_index'
  resources :spp_payments
  resources :spp_invoices
  resources :spp_categories
  resources :spp_students
  resources :spp_batches

  # Campaign
  resources :categories
  resources :donations
  resources :campaigns do
    member do
      get :contribute
    end
  end
  resources :comments

  # System
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :users
  resources :posts
  get "up" => "rails/health#show", as: :rails_health_check
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  belongs_to :category
  mount_uploader :picture, ImageUploader
  has_rich_text :content
  has_many :donations, dependent: :destroy
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :campaigns
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_rich_text :content
end

app/models/donation.rb
class Donation < ApplicationRecord
  belongs_to :campaign
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :pict, ImageUploader
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_rich_text :content
end

app/models/spp_batch.rb
class SppBatch < ApplicationRecord
  def start_at_year
    start_at.year
  end
end

app/models/spp_category.rb
class SppCategory < ApplicationRecord
end

app/models/spp_invoice.rb
class SppInvoice < ApplicationRecord
  belongs_to :spp_student
  belongs_to :spp_category
  has_many :spp_payments
end

app/models/spp_payment.rb
class SppPayment < ApplicationRecord
  belongs_to :spp_batch
  belongs_to :user, optional: true
  belongs_to :spp_student
  belongs_to :spp_invoice
end

app/models/spp_student.rb
class SppStudent < ApplicationRecord
  belongs_to :spp_batch
  has_many :spp_payments
  has_many :spp_invoices

  mount_uploader :pict, ImageUploader

  after_create :create_spp_invoices

  def create_spp_invoices
    spp_category = SppCategory.find_or_create_by(title: "SPP")

    spp_invoice = SppInvoice.create(
      spp_student_id: id,
      spp_category_id: spp_category.id,
      amount: 12_000_000,
      paid_amount: 0,
      status: "NEW",
    )

    # Create SPP Payments for the next 12 months
    (0..11).each do |i|
      due_date = spp_batch.start_at + i.months
      SppPayment.create!(
        spp_batch_id: spp_batch_id,
        spp_student_id: id,
        spp_invoice_id: spp_invoice.id,
        amount: 1_000_000,
        # user_id diambil dari user yg login
        # tipe : harus dimasukkan manual oleh bendahara
        # pay_at : harus dimasukkan manual oleh bendahara
      )
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy

  def admin?
    role == 'ADMIN'
  end

  def user?
    role == 'USER'
  end
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :set_donation, only: %i[ show edit update destroy ]

  # GET /donations or /donations.json
  def index
    @donations = Donation.all
  end

  # GET /donations/1 or /donations/1.json
  def show
  end

  # GET /donations/new
  def new
    @donation = Donation.new
  end

  # GET /donations/1/edit
  def edit
  end

  # POST /donations or /donations.json
  def create
    @donation = Donation.new(donation_params)

    respond_to do |format|
      if @donation.save
        format.html { redirect_to donation_url(@donation), notice: "Donation was successfully created." }
        format.json { render :show, status: :created, location: @donation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donations/1 or /donations/1.json
  def update
    respond_to do |format|
      if @donation.update(donation_params)
        format.html { redirect_to donation_url(@donation), notice: "Donation was successfully updated." }
        format.json { render :show, status: :ok, location: @donation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donations/1 or /donations/1.json
  def destroy
    @donation.destroy!

    respond_to do |format|
      format.html { redirect_to donations_url, notice: "Donation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donation
      @donation = Donation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def donation_params
      params.require(:donation).permit(:campaign_id, :amount, :name, :email, :telephone, :anonymous, :payment_type, :dua)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/spp_controller.rb
class SppController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def idr v
    number_to_currency( v.to_i, unit: "Rp", precision: 0, separator: ",", delimiter: ".", format: "%u%n,-")
  end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/spp_batches_helper.rb
module SppBatchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/donations/_donation.html.erb
<div id="<%= dom_id donation %>">
  <p>
    <strong>Campaign:</strong>
    <%= donation.campaign_id %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= donation.amount %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= donation.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= donation.email %>
  </p>

  <p>
    <strong>Telephone:</strong>
    <%= donation.telephone %>
  </p>

  <p>
    <strong>Anonymous:</strong>
    <%= donation.anonymous %>
  </p>

  <p>
    <strong>Payment type:</strong>
    <%= donation.payment_type %>
  </p>

  <p>
    <strong>Dua:</strong>
    <%= donation.dua %>
  </p>

</div>

app/views/donations/_form.html.erb
<%= form_with(model: donation) do |form| %>
  <% if donation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(donation.errors.count, "error") %> prohibited this donation from being saved:</h2>

      <ul>
        <% donation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :campaign_id, style: "display: block" %>
    <%= form.text_field :campaign_id %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.number_field :amount %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :telephone, style: "display: block" %>
    <%= form.text_field :telephone %>
  </div>

  <div>
    <%= form.label :anonymous, style: "display: block" %>
    <%= form.check_box :anonymous %>
  </div>

  <div>
    <%= form.label :payment_type, style: "display: block" %>
    <%= form.text_field :payment_type %>
  </div>

  <div>
    <%= form.label :dua, style: "display: block" %>
    <%= form.text_field :dua %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/donations/edit.html.erb
<h1>Editing donation</h1>

<%= render "form", donation: @donation %>

<br>

<div>
  <%= link_to "Show this donation", @donation %> |
  <%= link_to "Back to donations", donations_path %>
</div>

app/views/donations/index.html.erb
<h1>Donations</h1>

<div id="donations">
  <% @donations.each do |donation| %>
    <%= render donation %>
    <p>
      <%= link_to "Show this donation", donation %>
    </p>
  <% end %>
</div>

<%= link_to "New donation", new_donation_path %>

app/views/donations/new.html.erb
<h1>New donation</h1>

<%= render "form", donation: @donation %>

<br>

<div>
  <%= link_to "Back to donations", donations_path %>
</div>

app/views/donations/show.html.erb
<%= render @donation %>

<div>
  <%= link_to "Edit this donation", edit_donation_path(@donation) %> |
  <%= link_to "Back to donations", donations_path %>

  <%= button_to "Destroy this donation", @donation, method: :delete %>
</div>